### ISSUE TITLE
Allow running tests in parallel

### ISSUE THREAD

**Issue by orf** [Homebrew/homebrew-test-bot#596]
Hello :wave:

Some core formula like sqlite (https://github.com/Homebrew/homebrew-core/pull/74485) hit a recurring issue where builds take _forever_. Here's one that's been going [for over 9 hours](https://github.com/Homebrew/homebrew-core/actions/runs/722540993). It seems like it would be trivial to parallelize the `brew test-bot` command, especially as we are using Github Actions, and reduce the time it takes to check these changes in. For context, SQLite 3.35.3 has a nasty bug that is fixed in 3.35.4 and it would be nice to be able to release this without running into CI timeouts.

Github Actions allows you to create dynamic matrices based on prior steps. For example:

```yaml
jobs:
    whatever:
        steps:
            run: echo "::set-output name=matrix::$(some-command)"
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

    run_something:
         needs: whatever
         strategy:
             matrix:
                 something: ${{ fromJson(needs.whatever.outputs.matrix) }}
         steps:
            ....
```

In the above example we have a step that executes `some-command`, and uses the JSON output from this command to feed into the `run_something` matrix.

I propose that we adapt the `brew test-bot` command to support a dynamic matrix. We can do this quite simply: We add a `--matrix` flag of some kind that outputs a JSON array of shards. If `sqlite3` tests needs to build 1,000 packages, and we specify that each job should handle 100 packages then this would be a simple array of `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`. If we're building a package that needs to build only 200 packages to test, then it might just be `[1, 2]`. As this only really makes a difference on some core packages we don't want to always launch a matrix of 10 jobs if each one is only going to run 3 or 4 tests. So there's some smartness that could be added to account for this which is different from just `idx % total`.

The downstream test would depend on this output and would use the value to shard tests. So, given the above 1,000 packages that need to be tested across 10 different runners then we'd run `brew test-bot ${{ matrix.shard }} ${{ matrix.total_shards }}`, which would run 10% of the packages it needs to.

In theory this would result in a lot faster builds for packages that are heavily depended on. We could also run the `brew test-bot --matrix` command on a Ubuntu runner to save resources.

I'm not that familiar with Homebrew or the intricacies of how it's tested, so I hope this makes sense!
